/**
 * Returns the catalog of emergency helplines and direct service numbers.
 */
export const getHelplinesList = async () => {
  return [
    {
      id: 'helpline_112',
      title: 'National Emergency (ERSS)',
      number: '112',
      subtitle: 'All-in-one emergency helpline for Police, Fire & Medical Services',
      color: '#448AFF',
      icon: 'emergency',
      category: 'general',
    },
    {
      id: 'helpline_100',
      title: 'Police Helpline',
      number: '100',
      subtitle: 'Immediate police emergency response & law enforcement',
      color: '#536DFE',
      icon: 'local_police',
      category: 'police',
    },
    {
      id: 'helpline_1091',
      title: 'Women Helpline',
      number: '1091',
      subtitle: '24/7 emergency distress helpline for women safety',
      color: '#E040FB',
      icon: 'shield',
      category: 'women',
    },
    {
      id: 'helpline_181',
      title: 'Women Helpline (Domestic Abuse)',
      number: '181',
      subtitle: 'Support & counseling for women facing domestic violence',
      color: '#FF6E40',
      icon: 'health_and_safety',
      category: 'women',
    },
    {
      id: 'helpline_108',
      title: 'Medical Emergency & Ambulance',
      number: '108',
      subtitle: 'Emergency medical rescue & ambulance transport',
      color: '#FF5252',
      icon: 'medical_services',
      category: 'medical',
    },
    {
      id: 'helpline_101',
      title: 'Fire & Rescue Services',
      number: '101',
      subtitle: 'Firefighting, rescue operations & fire emergencies',
      color: '#FF6D00',
      icon: 'local_fire_department',
      category: 'fire',
    },
    {
      id: 'helpline_1098',
      title: 'Child Helpline (Childline)',
      number: '1098',
      subtitle: '24/7 emergency rescue & assistance for children in distress',
      color: '#FFAB00',
      icon: 'child_care',
      category: 'children',
    },
    {
      id: 'helpline_1930',
      title: 'National Cyber Crime Helpline',
      number: '1930',
      subtitle: 'Report financial cyber fraud & digital harassment',
      color: '#009688',
      icon: 'security',
      category: 'cyber',
    },
    {
      id: 'helpline_14416',
      title: 'Tele-MANAS Mental Health',
      number: '14416',
      subtitle: '24/7 free mental health counseling & crisis intervention',
      color: '#4CAF50',
      icon: 'psychology',
      category: 'mental_health',
    },
    {
      id: 'helpline_14567',
      title: 'Senior Citizen Helpline (Elder Line)',
      number: '14567',
      subtitle: 'Toll-free helpline for elder care & assistance',
      color: '#7C4DFF',
      icon: 'elderly',
      category: 'elderly',
    },
    {
      id: 'helpline_1033',
      title: 'National Highway Emergency',
      number: '1033',
      subtitle: '24/7 highway patrol & accident emergency assistance',
      color: '#795548',
      icon: 'minor_crash',
      category: 'highway',
    },
  ];
};
